name: music_player
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  cupertino_icons: ^1.0.8
  duration_picker: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  font_awesome_flutter: ^10.9.1
  luciq_flutter: ^18.0.0
  get_it: ^8.2.0
  intl: ^0.20.2
  just_audio: ^0.10.4
  marquee: ^2.3.0
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  on_audio_query_pluse: ^2.9.4
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  scrollable_positioned_list: ^0.3.8
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  stream_transform: ^2.1.1
  url_launcher: ^6.3.2
  volume_controller: ^3.4.0

objectbox:
  output_dir: core/services/database

dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  objectbox_generator: ^5.0.0
  very_good_analysis: ^9.0.0

flutter_native_splash:
  android: true
  ios: true
  color: "#060429"
  icon_background_color: "#060429"
  icon_background_color_dark: "#060429"
  image: assets/logo/app_logo.png
  branding: assets/logo/logo_branding.png
  android_gravity: center
  android_12:
    color: "#060429"
    image: assets/logo/app_logo.png
    branding: assets/logo/logo_branding.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/logo/
    - .env
