name: music_player
description: "A new Flutter project."

publish_to: "none"

version: 0.0.4+5

environment:
  sdk: ^3.8.1

dependencies:
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  auto_size_text: ^3.0.0
  bloc: ^9.0.1
  cupertino_icons: ^1.0.8
  duration_picker: ^1.2.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_spinkit: ^5.2.2
  font_awesome_flutter: ^10.9.1
  get_it: ^8.2.0
  intl: ^0.20.2
  just_audio: ^0.10.5
  marquee: ^2.3.0
  on_audio_query_pluse: ^3.0.5
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  scrollable_positioned_list: ^0.3.8
  see_more_text: ^1.1.1
  sentry_flutter: ^9.8.0
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  stream_transform: ^2.1.1
  url_launcher: ^6.3.2
  volume_controller: ^3.4.0
  wave_player: ^0.0.4


dev_dependencies:
  build_runner: ^2.5.4
  flutter_test:
    sdk: flutter
  sentry_dart_plugin: ^3.1.1
  very_good_analysis: ^9.0.0

flutter_native_splash:
  android: true
  ios: true
  color: "#060429"
  icon_background_color: "#060429"
  icon_background_color_dark: "#060429"
  image: assets/logo/app_logo.png
  branding: assets/logo/logo_branding.png
  android_gravity: center
  android_12:
    color: "#060429"
    image: assets/logo/app_logo.png
    branding: assets/logo/logo_branding.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/fonts/inter/
    - assets/fonts/vazirmatn/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-Italic.ttf
          style: italic
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/vazirmatn/Vazirmatn-Regular.ttf
        - asset: assets/fonts/vazirmatn/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/vazirmatn/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/vazirmatn/Vazirmatn-Bold.ttf
          weight: 700
sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: free-music-player
  org: talebr75
