name: music_player
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  on_audio_query_pluse: ^2.9.4
  just_audio: ^0.10.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  stream_transform: ^2.1.1
  marquee: ^2.3.0
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  get_it: ^8.2.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.5.3
  objectbox: ^4.3.0
  path_provider: ^2.1.5
  path: ^1.9.1
  objectbox_flutter_libs: ^4.3.0
  share_plus: ^11.1.0
  permission_handler: ^12.0.1
  duration_picker: ^1.2.0
  url_launcher: ^6.3.2
  font_awesome_flutter: ^10.10.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  scrollable_positioned_list: ^0.3.8
  

objectbox:
  output_dir: core/services/database

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  objectbox_generator: ^4.3.0
  build_runner: ^2.5.4

flutter_native_splash:
  android: true
  ios: true
  color: "#060429" 
  icon_background_color: "#060429"    
  icon_background_color_dark: "#060429"  
  image: assets/logo/app_logo.png 
  branding: assets/logo/logo_branding.png
  android_gravity: center  
  android_12:
    color: "#060429"
    image: assets/logo/app_logo.png   
    branding: assets/logo/logo_branding.png


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
