name: music_player
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  on_audio_query_pluse: ^2.9.4
  just_audio: ^0.10.4
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  stream_transform: ^2.1.1
  marquee: ^2.3.0
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  get_it: ^8.2.0
  auto_size_text: ^3.0.0
  shared_preferences: ^2.5.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
